---
name: Go
on:
  push:
    paths:
    - '**.go'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Prepare Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout codebase
      uses: actions/checkout@v2

    - name: Perform lint checks
      run: make lint

    - name: Perform format checks
      run: make simplify

    - name: Perform vet checks
      run: make vet

    - name: Run test suite
      run: make test
...
